### PR TITLE
Fix details on the initial letter height.

### PR DESCRIPTION
**Pull request by eschwab**

### CODE REVIEW

**Comment by henryso** [comment]
This is not true until we release 4.1, no?

**Comment by eroux** [comment]
Generally speaking, I think it's be best if the documentation indicates the version of Gregorio in which a feature is first implemented... So adding "starting with Gregorio 4.1..." would be best (and would make the PR "mergeable" right now)

**Comment by eschwab** [comment]
@eroux agreed.

However do we have a plan for keeping the web docs reasonably up to date for upcoming releases? Does it make sense though to have a planned release branch for the website (in this case something like `release-4.1`)? That way we can keep reasonably up to date on major documentation changes, at least internally. Thus when we make a release that requires changes on the website we don't have to try and remember what they are.

**Comment by eroux** [comment]
Sounds like a good idea. At the same time if we always document the version, maybe we can just push everything, even for versions not released yet

**Comment by rpspringuel** [comment]
The problem is that we don't technically know the version number until we decide to make a release.  Certainly we might be able to make a good guess at it (like we know the next version after 4.1 will be 5.0 because there's a user interface change that has to be accounted for).  But if once we get beyond that, we might get in a situation where early on it looks like all the changes are pointing to an enhancement release, but by the time we get there we determine that it's going to be a major one.  If we'd been publishing changes with the predicted release number on them, we'd have to go find them and change them to meet the actual release number.

Also, it might be confusing for a user to see a feature described as available in such-and-such release but not be able to find the download link for that release (because it's still in development).

**Comment by eroux** [comment]
That's true, let's do that only once a beta is out... So maybe just a `develop` (with doc for pre-beta) and `master` would be good? Anyway, @eschwab no need to wait for a `develop` branch for this one, just indicate that it's a 4.1 feature and we can merge

**Comment by rpspringuel** [comment]
Since this is changed functionality (as opposed to new) should we also note how the same effect was accomplished pre-4.1?

**Comment by eroux** [comment]
I think that would be good yes

**Comment by eschwab** [comment]
Updated.

It makes sense to use a similar branching system for this repo as the main one, as @eroux already proposed.

**Comment by eroux** [comment]
I'm ok for this to be merged, thanks!

**Comment by rpspringuel** [comment]
Looks good to me.

**Pull request merged**
