### PR TITLE
Web site updates

### PR DESCRIPTION
**Pull request by gabrielmass**
This pull request contains revisions to the contents and style of Gregorio website
http://gregorio-project.github.io/

The changes are in the following areas:
- style.css: use the Google font Crimson Text instead of the outdated "calligraphic" font and New Century Schoolbook
- style.css: make h2, h3, and h4 headers slightly larger for readability of the small sizes
- style.css: no need to center h1 headers. Left-justified is more readable
- style.css: make navigation menu slightly wider, text area of page slightly narrower.
- multiple HTML files: found and fixed broken links
- multiple HTML files: numerous prose edits for clarity and English style
- legalissues.html: revised the summary of US copyright law to correct some unclear details
- gregorio-menu.js (new): a simple Javascript routine to write the navigation menu.  This lets us define the menu in one file instead of in 20 HTML files

The draft version can be read at http://music.chonak.com/ (temporary website).

### CODE REVIEW

**Comment by eroux** [comment]
I globally agree, but on the draft website, there are blue lines that look a bit strange, and the vertical one doesn't go down to the bottom of my screen... Also, on the legal issue page, initials at each paragraph could be avoided

**Comment by eroux** [comment]
It's a good first step towards something more modern, the ideal would be to rebuild it in angular 2 + material, but that's for next year at least...

**Comment by gabrielmass** [comment]
Changed the blue lines to #a97359 to match King David logo

**Comment by eroux** [comment]
Thanks! But the divider should also go to the bottom of the screen in all cases

**Comment by gabrielmass** [comment]
Added commit ca7a664 to fix divider and introduce drop-cap on first paragraph of page (replacing previous treatment of first initial)

**Comment by eroux** [comment]
Thanks a lot! Maybe a bit more top, left and right margins to the main frame would make it look a bit better, but that's not blocking

**Comment by gabrielmass** [comment]
Any comments on the new page?
( draft at: http://music.chonak.com/introduction-web.html )

**Comment by henryso** [comment]
I'm not a particularly good person to ask about these things, but I think it looks nifty.

**Comment by eroux** [comment]
I think so too, let's merge

**Pull request merged**
